"""
Module: config_imports.py

Author: Michael Economou
Date: 2025-05-31

config_imports.py
Centralized config imports to reduce clutter in main files.
Re-exports commonly used configuration constants.
"""

from config import (
    ALLOWED_EXTENSIONS,
    APP_AUTHOR,
    APP_NAME,
    APP_VERSION,
    COLUMN_SHORTCUTS,
    DIALOG_PATHS,
    FILE_TABLE_COLUMN_CONFIG,
    FILE_TABLE_SHORTCUTS,
    GLOBAL_SHORTCUTS,
    LARGE_SCREEN_MIN_HEIGHT,
    LARGE_SCREEN_MIN_WIDTH,
    LEFT_CENTER_RIGHT_SPLIT_RATIO,
    LEFT_PANEL_MAX_WIDTH,
    LEFT_PANEL_MIN_WIDTH,
    LOG_FORMAT,
    LOG_LEVEL,
    MAIN_WINDOW_GEOMETRY,
    MAIN_WINDOW_STATE,
    METADATA_TREE_COLUMN_WIDTHS,
    METADATA_TREE_USE_CUSTOM_DELEGATE,
    PREVIEW_COLUMN_WIDTH,
    PREVIEW_MIN_WIDTH,
    RIGHT_PANEL_MAX_WIDTH,
    RIGHT_PANEL_MIN_WIDTH,
    SCREEN_SIZE_BREAKPOINTS,
    SCREEN_SIZE_PERCENTAGES,
    TOP_BOTTOM_SPLIT_RATIO,
    ULTRA_WIDE_SCREEN_THRESHOLD,
    UNDO_REDO_SETTINGS,
    WIDE_SCREEN_THRESHOLD,
    WINDOW_HEIGHT,
    WINDOW_MIN_HEIGHT,
    WINDOW_MIN_SMART_HEIGHT,
    WINDOW_MIN_SMART_WIDTH,
    WINDOW_MIN_WIDTH,
    WINDOW_WIDTH,
)

# Re-export all config constants
__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "APP_AUTHOR",
    "LOG_LEVEL",
    "LOG_FORMAT",
    "DIALOG_PATHS",
    "FILE_TABLE_COLUMN_CONFIG",
    "FILE_TABLE_SHORTCUTS",
    "GLOBAL_SHORTCUTS",
    "COLUMN_SHORTCUTS",
    "METADATA_TREE_COLUMN_WIDTHS",
    "METADATA_TREE_USE_CUSTOM_DELEGATE",
    "MAIN_WINDOW_GEOMETRY",
    "MAIN_WINDOW_STATE",
    "TOP_BOTTOM_SPLIT_RATIO",
    "LEFT_CENTER_RIGHT_SPLIT_RATIO",
    "WINDOW_WIDTH",
    "WINDOW_HEIGHT",
    "WINDOW_MIN_WIDTH",
    "WINDOW_MIN_HEIGHT",
    "ALLOWED_EXTENSIONS",
    "LEFT_PANEL_MIN_WIDTH",
    "LEFT_PANEL_MAX_WIDTH",
    "RIGHT_PANEL_MIN_WIDTH",
    "RIGHT_PANEL_MAX_WIDTH",
    "WIDE_SCREEN_THRESHOLD",
    "ULTRA_WIDE_SCREEN_THRESHOLD",
    "LARGE_SCREEN_MIN_HEIGHT",
    "LARGE_SCREEN_MIN_WIDTH",
    "SCREEN_SIZE_BREAKPOINTS",
    "SCREEN_SIZE_PERCENTAGES",
    "WINDOW_MIN_SMART_HEIGHT",
    "WINDOW_MIN_SMART_WIDTH",
    "PREVIEW_COLUMN_WIDTH",
    "PREVIEW_MIN_WIDTH",
    "UNDO_REDO_SETTINGS",
]
