# Type stub for auto-generated fonts_rc module.
# The actual fonts_rc.py is generated by pyrcc5 from fonts.qrc (~100K LOC).
# To generate: python scripts/generate_fonts_rc.py
#
# This module only registers Qt resources via side effects - no public API.
