"""Module: oncutf.config.

Author: Michael Economou
Date: 2026-01-01

Configuration package for oncutf application.

This package organizes configuration into logical modules:
- app: Application info, debug flags, logging
- paths: File paths, extensions, validation patterns
- ui: UI settings, themes, colors, fonts
- columns: Column configurations for tables and trees
- features: Feature flags, external tools, limits
- shortcuts: Keyboard shortcuts

All settings are re-exported from this module for backward compatibility:
    from oncutf.config import APP_NAME, THEME_COLORS  # Works as before
"""

# oncutf.config.app
from oncutf.config.app import (
    APP_AUTHOR,
    APP_NAME,
    APP_VERSION,
    BACKUP_FILENAME_FORMAT,
    BACKUP_TIMESTAMP_FORMAT,
    CONFIG_AUTO_SAVE_DELAY,
    CONFIG_AUTO_SAVE_ENABLED,
    CONFIG_CACHE_ENABLED,
    CONFIG_CACHE_FLUSH_ON_SAVE,
    CONFIG_SAVE_ON_DIALOG_CLOSE,
    CONFIG_SAVE_ON_EXIT,
    DEBUG_FRESH_START,
    DEFAULT_BACKUP_COUNT,
    DEFAULT_BACKUP_INTERVAL,
    DEFAULT_PERIODIC_BACKUP_ENABLED,
    DEV_SIMULATE_SCREEN,
    DEV_SIMULATED_SCREEN,
    DIALOG_PATHS,
    ENABLE_DEBUG_LOG_FILE,
    EXPORT_DATE_FORMAT,
    LOG_CONSOLE_LEVEL,
    LOG_DEBUG_FILE_BACKUP_COUNT,
    LOG_DEBUG_FILE_ENABLED,
    LOG_DEBUG_FILE_LEVEL,
    LOG_DEBUG_FILE_MAX_BYTES,
    LOG_FILE_BACKUP_COUNT,
    LOG_FILE_LEVEL,
    LOG_FILE_MAX_BYTES,
    LOG_FORMAT,
    LOG_LEVEL,
    LOG_TO_CONSOLE,
    LOG_TO_FILE,
    MAIN_WINDOW_GEOMETRY,
    MAIN_WINDOW_STATE,
    SHOW_DEV_ONLY_IN_CONSOLE,
    WINDOW_TITLE,
)

# oncutf.config.columns
from oncutf.config.columns import (
    COLUMN_RESIZE_BEHAVIOR,
    COLUMN_SHORTCUTS,
    FILE_TABLE_COLUMN_CONFIG,
    GLOBAL_MIN_COLUMN_WIDTH,
    HASH_LIST_COLUMN_CONFIG,
    METADATA_TREE_COLUMN_CONFIG,
)

# oncutf.config.features
from oncutf.config.features import (
    AUTO_COLOR_FOLDERS_ENABLED,
    AUTO_COLOR_FOLDERS_SHORTCUT,
    AUTO_COLOR_MAX_RETRIES,
    AUTO_COLOR_MIN_BRIGHTNESS,
    COMMAND_TYPES,
    EXIFTOOL_TIMEOUT_BATCH_BASE,
    EXIFTOOL_TIMEOUT_BATCH_PER_FILE,
    EXIFTOOL_TIMEOUT_EXTENDED,
    EXIFTOOL_TIMEOUT_FAST,
    EXIFTOOL_TIMEOUT_WRITE,
    EXTENDED_METADATA_SIZE_LIMIT_MB,
    LARGE_FOLDER_WARNING_THRESHOLD,
    PARALLEL_HASH_MAX_WORKERS,
    SAVE_OPERATION_SETTINGS,
    UNDO_REDO_SETTINGS,
    USE_PARALLEL_HASH_WORKER,
    USE_PREVIEW_BACKGROUND,
    FeatureAvailability,
)

# oncutf.config.paths
from oncutf.config.paths import (
    ALLOWED_EXTENSIONS,
    ALLOWED_FILENAME_CHARS,
    AUTO_RENAME_COMPANION_FILES,
    COMPANION_FILES_ENABLED,
    DEFAULT_COMPANION_FILE_MODE,
    INVALID_FILENAME_CHARS,
    INVALID_FILENAME_MARKER,
    INVALID_TRAILING_CHARS,
    LOAD_COMPANION_METADATA,
    SHOW_COMPANION_FILES_IN_TABLE,
    USE_BINARY_UNITS,
    USE_LOCALE_DECIMAL_SEPARATOR,
    CompanionFileMode,
)

# oncutf.config.shortcuts
from oncutf.config.shortcuts import (
    FILE_TABLE_SHORTCUTS,
    FILE_TREE_SHORTCUTS,
    GLOBAL_SHORTCUTS,
    METADATA_TREE_SHORTCUTS,
    PREVIEW_SHORTCUTS,
    REFRESH_KEY,
)

# oncutf.config.ui
from oncutf.config.ui import (
    COLOR_GRID_COLS,
    COLOR_GRID_ROWS,
    COLOR_PICKER_IMAGE,
    COLOR_SWATCH_SIZE,
    CONTENT_MARGINS,
    CONTEXT_MENU_COLORS,
    DEFAULT_DATA_FONT,
    DEFAULT_PREVIEW_ICON_SIZE,
    DEFAULT_UI_FONT,
    EXTENDED_METADATA_BG_COLOR,
    EXTENDED_METADATA_COLOR,
    FAST_METADATA_BG_COLOR,
    FAST_METADATA_COLOR,
    FILE_LOADING_BG_COLOR,
    FILE_LOADING_COLOR,
    FILE_TAG_COLOR_ARRAY,
    FONT_FAMILIES,
    FONT_SIZE_ADJUSTMENTS,
    HASH_CALCULATION_BG_COLOR,
    HASH_CALCULATION_COLOR,
    HASH_LIST_CONTENT_MARGINS,
    HASH_LIST_FONT_SIZE,
    HASH_LIST_HEADER_ALIGNMENT,
    HASH_LIST_LABEL_BACKGROUND,
    HASH_LIST_ROW_HEIGHT,
    HASH_LIST_WINDOW_DEFAULT_HEIGHT,
    HASH_LIST_WINDOW_DEFAULT_WIDTH,
    HASH_LIST_WINDOW_MAX_HEIGHT,
    HASH_LIST_WINDOW_MIN_HEIGHT,
    ICON_SIZES,
    LARGE_SCREEN_MIN_HEIGHT,
    LARGE_SCREEN_MIN_WIDTH,
    LEFT_PANEL_MAX_WIDTH,
    LEFT_PANEL_MIN_WIDTH,
    LOWER_SECTION_LEFT_MIN_SIZE,
    LOWER_SECTION_RIGHT_MIN_SIZE,
    LOWER_SECTION_SPLIT_RATIO,
    MAX_LABEL_LENGTH,
    METADATA_ICON_COLORS,
    METADATA_TREE_COLUMN_WIDTHS,
    METADATA_TREE_USE_CUSTOM_DELEGATE,
    METADATA_TREE_USE_PROXY,
    PREVIEW_COLORS,
    PREVIEW_COLUMN_WIDTH,
    PREVIEW_INDICATOR_BORDER,
    PREVIEW_INDICATOR_SHAPE,
    PREVIEW_INDICATOR_SIZE,
    PREVIEW_MIN_WIDTH,
    QLABEL_BORDER_GRAY,
    QLABEL_DARK_BG,
    QLABEL_DARK_BORDER,
    QLABEL_ERROR_BG,
    QLABEL_ERROR_TEXT,
    QLABEL_INFO_TEXT,
    QLABEL_MUTED_TEXT,
    QLABEL_PRIMARY_TEXT,
    QLABEL_SECONDARY_TEXT,
    QLABEL_TERTIARY_TEXT,
    QLABEL_WHITE_TEXT,
    RESULTS_TABLE_DEFAULT_HEIGHT,
    RESULTS_TABLE_DEFAULT_WIDTH,
    RESULTS_TABLE_LEFT_COLUMN_WIDTH,
    RESULTS_TABLE_MAX_HEIGHT,
    RESULTS_TABLE_MIN_HEIGHT,
    RESULTS_TABLE_MIN_WIDTH,
    RESULTS_TABLE_RIGHT_COLUMN_WIDTH,
    RIGHT_PANEL_MAX_WIDTH,
    RIGHT_PANEL_MIN_WIDTH,
    SAVE_BG_COLOR,
    SAVE_COLOR,
    SCREEN_SIZE_BREAKPOINTS,
    SCREEN_SIZE_PERCENTAGES,
    SPLASH_SCREEN_DURATION,
    STATUS_AUTO_RESET_DELAY,
    STATUS_COLORS,
    THEME_COLORS,
    THEME_NAME,
    THEME_TOKENS,
    TOOLTIP_DURATION,
    TOOLTIP_POSITION_OFFSET,
    TOP_BOTTOM_SPLIT_RATIO,
    ULTRA_WIDE_SCREEN_THRESHOLD,
    USE_EMBEDDED_FONTS,
    WAIT_CURSOR_SUPPRESS_AFTER_SPLASH_MS,
    WIDE_SCREEN_THRESHOLD,
    WIDGET_FONTS,
    WINDOW_HEIGHT,
    WINDOW_MIN_HEIGHT,
    WINDOW_MIN_SMART_HEIGHT,
    WINDOW_MIN_SMART_WIDTH,
    WINDOW_MIN_WIDTH,
    WINDOW_WIDTH,
    get_ui_font_family,
)
