"""
config_imports.py

Author: Michael Economou
Date: 2025-05-01

Centralized config imports to reduce clutter in main files.
Re-exports commonly used configuration constants.
"""

from config import (
    ALLOWED_EXTENSIONS,
    APP_NAME,
    APP_VERSION,
    DEFAULT_SKIP_METADATA,
    DEV_SIMULATE_SCREEN,
    DEV_SIMULATED_SCREEN,
    EXTENDED_METADATA_SIZE_LIMIT_MB,
    FILE_TABLE_COLUMN_WIDTHS,
    LARGE_FOLDER_WARNING_THRESHOLD,
    LARGE_SCREEN_MIN_HEIGHT,
    LARGE_SCREEN_MIN_WIDTH,
    LEFT_CENTER_RIGHT_SPLIT_RATIO,
    LEFT_PANEL_MIN_WIDTH,
    LEFT_PANEL_MAX_WIDTH,
    METADATA_TREE_COLUMN_WIDTHS,
    RIGHT_PANEL_MIN_WIDTH,
    RIGHT_PANEL_MAX_WIDTH,
    SCREEN_SIZE_BREAKPOINTS,
    SCREEN_SIZE_PERCENTAGES,
    STATUS_COLORS,
    TOP_BOTTOM_SPLIT_RATIO,
    TREE_EXPAND_MODE,
    ULTRA_WIDE_SCREEN_THRESHOLD,
    WIDE_SCREEN_THRESHOLD,
    WINDOW_HEIGHT,
    WINDOW_MIN_HEIGHT,
    WINDOW_MIN_SMART_HEIGHT,
    WINDOW_MIN_SMART_WIDTH,
    WINDOW_MIN_WIDTH,
    WINDOW_WIDTH,
)

# Re-export all config constants
__all__ = [
    'ALLOWED_EXTENSIONS',
    'APP_NAME',
    'APP_VERSION',
    'DEFAULT_SKIP_METADATA',
    'DEV_SIMULATE_SCREEN',
    'DEV_SIMULATED_SCREEN',
    'EXTENDED_METADATA_SIZE_LIMIT_MB',
    'FILE_TABLE_COLUMN_WIDTHS',
    'LARGE_FOLDER_WARNING_THRESHOLD',
    'LARGE_SCREEN_MIN_HEIGHT',
    'LARGE_SCREEN_MIN_WIDTH',
    'LEFT_CENTER_RIGHT_SPLIT_RATIO',
    'LEFT_PANEL_MIN_WIDTH',
    'LEFT_PANEL_MAX_WIDTH',
    'METADATA_TREE_COLUMN_WIDTHS',
    'RIGHT_PANEL_MIN_WIDTH',
    'RIGHT_PANEL_MAX_WIDTH',
    'SCREEN_SIZE_BREAKPOINTS',
    'SCREEN_SIZE_PERCENTAGES',
    'STATUS_COLORS',
    'TOP_BOTTOM_SPLIT_RATIO',
    'TREE_EXPAND_MODE',
    'ULTRA_WIDE_SCREEN_THRESHOLD',
    'WIDE_SCREEN_THRESHOLD',
    'WINDOW_HEIGHT',
    'WINDOW_MIN_HEIGHT',
    'WINDOW_MIN_SMART_HEIGHT',
    'WINDOW_MIN_SMART_WIDTH',
    'WINDOW_MIN_WIDTH',
    'WINDOW_WIDTH',
]
