name: Run Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies for GUI testing
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libfontconfig1 libglib2.0-0 libxcb-xfixes0

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Xvfb display server
      run: |
        sudo /usr/bin/Xvfb :99 -screen 0 1920x1080x24 -ac +extension GLX &
        sleep 3

    - name: Test PyQt5 setup
      env:
        DISPLAY: :99
        QT_QPA_PLATFORM: offscreen
      run: |
        python -c "from PyQt5.QtWidgets import QApplication; app = QApplication([]); print('PyQt5 OK')"

    - name: Run tests (basic first)
      env:
        CI: true
        QT_QPA_PLATFORM: offscreen
        DISPLAY: :99
      run: |
        timeout 10m pytest tests/ -v -x --tb=short

    - name: Run tests with coverage
      env:
        CI: true
        QT_QPA_PLATFORM: offscreen
        DISPLAY: :99
      run: |
        timeout 5m pytest tests/ -v --cov=widgets --cov=modules --cov=utils --cov=main_window --cov-report=term-missing
